name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --registry https://registry.npmjs.org
      - name: Prettier
        run: npm run format:check
      - name: Lint
        run: npm run lint
      # - name: Test
      #   run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --registry https://registry.npmjs.org
      - name: Build
        run: npm run build
